[package]
name = "librclone"
version = "0.10.0"
edition = "2021"
rust-version = "1.82"
description = "Rust bindings for librclone."
documentation = "https://docs.rs/librclone"
readme = "README.md"
repository = "https://github.com/trevyn/librclone"
license = "MIT OR Apache-2.0 OR CC0-1.0"
keywords = ["rclone"]

[workspace]
members = ["examples/basic", "librclone-sys"]

[dependencies]
librclone-sys = { path = "librclone-sys", version = "=0.10.0" }
